/**
 * Digraphs Data - Two letters that make one sound
 * Following synthetic phonics methodology
 */

export interface DigraphItem {
  id: string;
  digraph: string;
  sound: string;
  phonemeSpelling: string; // For speech synthesis
  description: string;
  position: "initial" | "final" | "both"; // Where digraph appears in words
  exampleWord: string;
  color: string;
}

export interface DigraphWord {
  id: string;
  word: string;
  digraphId: string;
  digraphPosition: "initial" | "final" | "medial";
  syllables: string[];
  phonemes: string[];
  difficulty: 1 | 2 | 3; // 1 = easy CVC+digraph, 2 = CCVC/CVCC, 3 = multisyllabic
  imageKeyword: string; // For image search
}

// 8 Core Digraphs
export const DIGRAPHS: DigraphItem[] = [
  {
    id: "sh",
    digraph: "sh",
    sound: "ʃ",
    phonemeSpelling: "shh",
    description: "Put your finger to your lips and say 'shh'",
    position: "both",
    exampleWord: "ship",
    color: "bg-blue-400",
  },
  {
    id: "ch",
    digraph: "ch",
    sound: "tʃ",
    phonemeSpelling: "ch",
    description: "Like a train: choo choo!",
    position: "both",
    exampleWord: "chip",
    color: "bg-red-400",
  },
  {
    id: "th-voiced",
    digraph: "th",
    sound: "ð",
    phonemeSpelling: "thh",
    description: "Soft th - put your tongue between your teeth",
    position: "both",
    exampleWord: "this",
    color: "bg-green-400",
  },
  {
    id: "th-unvoiced",
    digraph: "th",
    sound: "θ",
    phonemeSpelling: "th",
    description: "Hard th - blow air over your tongue",
    position: "both",
    exampleWord: "think",
    color: "bg-teal-400",
  },
  {
    id: "wh",
    digraph: "wh",
    sound: "w",
    phonemeSpelling: "wh",
    description: "Like blowing out a candle",
    position: "initial",
    exampleWord: "whale",
    color: "bg-cyan-400",
  },
  {
    id: "ph",
    digraph: "ph",
    sound: "f",
    phonemeSpelling: "f",
    description: "Makes the same sound as 'f'",
    position: "both",
    exampleWord: "phone",
    color: "bg-purple-400",
  },
  {
    id: "ck",
    digraph: "ck",
    sound: "k",
    phonemeSpelling: "k",
    description: "A short, quick 'k' sound at the end",
    position: "final",
    exampleWord: "duck",
    color: "bg-yellow-400",
  },
  {
    id: "ng",
    digraph: "ng",
    sound: "ŋ",
    phonemeSpelling: "ng",
    description: "Hum through your nose",
    position: "final",
    exampleWord: "ring",
    color: "bg-orange-400",
  },
];

// Comprehensive word list organized by digraph (~100 words total)
export const DIGRAPH_WORDS: DigraphWord[] = [
  // SH words (15 words)
  {
    id: "sh-ship",
    word: "ship",
    digraphId: "sh",
    digraphPosition: "initial",
    syllables: ["ship"],
    phonemes: ["sh", "i", "p"],
    difficulty: 1,
    imageKeyword: "ship boat",
  },
  {
    id: "sh-shop",
    word: "shop",
    digraphId: "sh",
    digraphPosition: "initial",
    syllables: ["shop"],
    phonemes: ["sh", "o", "p"],
    difficulty: 1,
    imageKeyword: "shop store",
  },
  {
    id: "sh-shell",
    word: "shell",
    digraphId: "sh",
    digraphPosition: "initial",
    syllables: ["shell"],
    phonemes: ["sh", "e", "ll"],
    difficulty: 1,
    imageKeyword: "seashell",
  },
  {
    id: "sh-shed",
    word: "shed",
    digraphId: "sh",
    digraphPosition: "initial",
    syllables: ["shed"],
    phonemes: ["sh", "e", "d"],
    difficulty: 1,
    imageKeyword: "garden shed",
  },
  {
    id: "sh-sheep",
    word: "sheep",
    digraphId: "sh",
    digraphPosition: "initial",
    syllables: ["sheep"],
    phonemes: ["sh", "ee", "p"],
    difficulty: 1,
    imageKeyword: "sheep animal",
  },
  {
    id: "sh-fish",
    word: "fish",
    digraphId: "sh",
    digraphPosition: "final",
    syllables: ["fish"],
    phonemes: ["f", "i", "sh"],
    difficulty: 1,
    imageKeyword: "fish",
  },
  {
    id: "sh-dish",
    word: "dish",
    digraphId: "sh",
    digraphPosition: "final",
    syllables: ["dish"],
    phonemes: ["d", "i", "sh"],
    difficulty: 1,
    imageKeyword: "dish plate",
  },
  {
    id: "sh-wish",
    word: "wish",
    digraphId: "sh",
    digraphPosition: "final",
    syllables: ["wish"],
    phonemes: ["w", "i", "sh"],
    difficulty: 1,
    imageKeyword: "wish star",
  },
  {
    id: "sh-brush",
    word: "brush",
    digraphId: "sh",
    digraphPosition: "final",
    syllables: ["brush"],
    phonemes: ["b", "r", "u", "sh"],
    difficulty: 2,
    imageKeyword: "brush",
  },
  {
    id: "sh-crash",
    word: "crash",
    digraphId: "sh",
    digraphPosition: "final",
    syllables: ["crash"],
    phonemes: ["c", "r", "a", "sh"],
    difficulty: 2,
    imageKeyword: "crash",
  },
  {
    id: "sh-trash",
    word: "trash",
    digraphId: "sh",
    digraphPosition: "final",
    syllables: ["trash"],
    phonemes: ["t", "r", "a", "sh"],
    difficulty: 2,
    imageKeyword: "trash can",
  },
  {
    id: "sh-shirt",
    word: "shirt",
    digraphId: "sh",
    digraphPosition: "initial",
    syllables: ["shirt"],
    phonemes: ["sh", "ir", "t"],
    difficulty: 2,
    imageKeyword: "shirt",
  },
  {
    id: "sh-shark",
    word: "shark",
    digraphId: "sh",
    digraphPosition: "initial",
    syllables: ["shark"],
    phonemes: ["sh", "ar", "k"],
    difficulty: 2,
    imageKeyword: "shark",
  },
  {
    id: "sh-shine",
    word: "shine",
    digraphId: "sh",
    digraphPosition: "initial",
    syllables: ["shine"],
    phonemes: ["sh", "i", "ne"],
    difficulty: 2,
    imageKeyword: "sunshine",
  },
  {
    id: "sh-shadow",
    word: "shadow",
    digraphId: "sh",
    digraphPosition: "initial",
    syllables: ["sha", "dow"],
    phonemes: ["sh", "a", "d", "ow"],
    difficulty: 3,
    imageKeyword: "shadow",
  },

  // CH words (13 words)
  {
    id: "ch-chip",
    word: "chip",
    digraphId: "ch",
    digraphPosition: "initial",
    syllables: ["chip"],
    phonemes: ["ch", "i", "p"],
    difficulty: 1,
    imageKeyword: "chip potato",
  },
  {
    id: "ch-chat",
    word: "chat",
    digraphId: "ch",
    digraphPosition: "initial",
    syllables: ["chat"],
    phonemes: ["ch", "a", "t"],
    difficulty: 1,
    imageKeyword: "chat talk",
  },
  {
    id: "ch-chop",
    word: "chop",
    digraphId: "ch",
    digraphPosition: "initial",
    syllables: ["chop"],
    phonemes: ["ch", "o", "p"],
    difficulty: 1,
    imageKeyword: "chop wood",
  },
  {
    id: "ch-chin",
    word: "chin",
    digraphId: "ch",
    digraphPosition: "initial",
    syllables: ["chin"],
    phonemes: ["ch", "i", "n"],
    difficulty: 1,
    imageKeyword: "chin face",
  },
  {
    id: "ch-chess",
    word: "chess",
    digraphId: "ch",
    digraphPosition: "initial",
    syllables: ["chess"],
    phonemes: ["ch", "e", "ss"],
    difficulty: 1,
    imageKeyword: "chess game",
  },
  {
    id: "ch-chair",
    word: "chair",
    digraphId: "ch",
    digraphPosition: "initial",
    syllables: ["chair"],
    phonemes: ["ch", "air"],
    difficulty: 2,
    imageKeyword: "chair",
  },
  {
    id: "ch-cheese",
    word: "cheese",
    digraphId: "ch",
    digraphPosition: "initial",
    syllables: ["cheese"],
    phonemes: ["ch", "ee", "se"],
    difficulty: 2,
    imageKeyword: "cheese",
  },
  {
    id: "ch-cherry",
    word: "cherry",
    digraphId: "ch",
    digraphPosition: "initial",
    syllables: ["cher", "ry"],
    phonemes: ["ch", "e", "rr", "y"],
    difficulty: 3,
    imageKeyword: "cherry fruit",
  },
  {
    id: "ch-rich",
    word: "rich",
    digraphId: "ch",
    digraphPosition: "final",
    syllables: ["rich"],
    phonemes: ["r", "i", "ch"],
    difficulty: 1,
    imageKeyword: "rich gold",
  },
  {
    id: "ch-much",
    word: "much",
    digraphId: "ch",
    digraphPosition: "final",
    syllables: ["much"],
    phonemes: ["m", "u", "ch"],
    difficulty: 1,
    imageKeyword: "much many",
  },
  {
    id: "ch-such",
    word: "such",
    digraphId: "ch",
    digraphPosition: "final",
    syllables: ["such"],
    phonemes: ["s", "u", "ch"],
    difficulty: 1,
    imageKeyword: "such",
  },
  {
    id: "ch-lunch",
    word: "lunch",
    digraphId: "ch",
    digraphPosition: "final",
    syllables: ["lunch"],
    phonemes: ["l", "u", "n", "ch"],
    difficulty: 2,
    imageKeyword: "lunch food",
  },
  {
    id: "ch-bench",
    word: "bench",
    digraphId: "ch",
    digraphPosition: "final",
    syllables: ["bench"],
    phonemes: ["b", "e", "n", "ch"],
    difficulty: 2,
    imageKeyword: "bench park",
  },

  // TH voiced words (12 words)
  {
    id: "th-this",
    word: "this",
    digraphId: "th-voiced",
    digraphPosition: "initial",
    syllables: ["this"],
    phonemes: ["th", "i", "s"],
    difficulty: 1,
    imageKeyword: "pointing",
  },
  {
    id: "th-that",
    word: "that",
    digraphId: "th-voiced",
    digraphPosition: "initial",
    syllables: ["that"],
    phonemes: ["th", "a", "t"],
    difficulty: 1,
    imageKeyword: "pointing",
  },
  {
    id: "th-them",
    word: "them",
    digraphId: "th-voiced",
    digraphPosition: "initial",
    syllables: ["them"],
    phonemes: ["th", "e", "m"],
    difficulty: 1,
    imageKeyword: "people group",
  },
  {
    id: "th-then",
    word: "then",
    digraphId: "th-voiced",
    digraphPosition: "initial",
    syllables: ["then"],
    phonemes: ["th", "e", "n"],
    difficulty: 1,
    imageKeyword: "clock time",
  },
  {
    id: "th-the",
    word: "the",
    digraphId: "th-voiced",
    digraphPosition: "initial",
    syllables: ["the"],
    phonemes: ["th", "e"],
    difficulty: 1,
    imageKeyword: "letter",
  },
  {
    id: "th-there",
    word: "there",
    digraphId: "th-voiced",
    digraphPosition: "initial",
    syllables: ["there"],
    phonemes: ["th", "air"],
    difficulty: 2,
    imageKeyword: "pointing there",
  },
  {
    id: "th-these",
    word: "these",
    digraphId: "th-voiced",
    digraphPosition: "initial",
    syllables: ["these"],
    phonemes: ["th", "ee", "z"],
    difficulty: 2,
    imageKeyword: "these items",
  },
  {
    id: "th-those",
    word: "those",
    digraphId: "th-voiced",
    digraphPosition: "initial",
    syllables: ["those"],
    phonemes: ["th", "o", "z"],
    difficulty: 2,
    imageKeyword: "those items",
  },
  {
    id: "th-mother",
    word: "mother",
    digraphId: "th-voiced",
    digraphPosition: "medial",
    syllables: ["mo", "ther"],
    phonemes: ["m", "u", "th", "er"],
    difficulty: 3,
    imageKeyword: "mother mom",
  },
  {
    id: "th-father",
    word: "father",
    digraphId: "th-voiced",
    digraphPosition: "medial",
    syllables: ["fa", "ther"],
    phonemes: ["f", "a", "th", "er"],
    difficulty: 3,
    imageKeyword: "father dad",
  },
  {
    id: "th-brother",
    word: "brother",
    digraphId: "th-voiced",
    digraphPosition: "medial",
    syllables: ["bro", "ther"],
    phonemes: ["b", "r", "u", "th", "er"],
    difficulty: 3,
    imageKeyword: "brother",
  },
  {
    id: "th-weather",
    word: "weather",
    digraphId: "th-voiced",
    digraphPosition: "medial",
    syllables: ["wea", "ther"],
    phonemes: ["w", "e", "th", "er"],
    difficulty: 3,
    imageKeyword: "weather",
  },

  // TH unvoiced words (12 words)
  {
    id: "th-thin",
    word: "thin",
    digraphId: "th-unvoiced",
    digraphPosition: "initial",
    syllables: ["thin"],
    phonemes: ["th", "i", "n"],
    difficulty: 1,
    imageKeyword: "thin skinny",
  },
  {
    id: "th-thick",
    word: "thick",
    digraphId: "th-unvoiced",
    digraphPosition: "initial",
    syllables: ["thick"],
    phonemes: ["th", "i", "ck"],
    difficulty: 1,
    imageKeyword: "thick",
  },
  {
    id: "th-thing",
    word: "thing",
    digraphId: "th-unvoiced",
    digraphPosition: "initial",
    syllables: ["thing"],
    phonemes: ["th", "i", "ng"],
    difficulty: 1,
    imageKeyword: "thing object",
  },
  {
    id: "th-think",
    word: "think",
    digraphId: "th-unvoiced",
    digraphPosition: "initial",
    syllables: ["think"],
    phonemes: ["th", "i", "nk"],
    difficulty: 2,
    imageKeyword: "think brain",
  },
  {
    id: "th-thumb",
    word: "thumb",
    digraphId: "th-unvoiced",
    digraphPosition: "initial",
    syllables: ["thumb"],
    phonemes: ["th", "u", "m"],
    difficulty: 1,
    imageKeyword: "thumb",
  },
  {
    id: "th-thank",
    word: "thank",
    digraphId: "th-unvoiced",
    digraphPosition: "initial",
    syllables: ["thank"],
    phonemes: ["th", "a", "nk"],
    difficulty: 2,
    imageKeyword: "thank you",
  },
  {
    id: "th-three",
    word: "three",
    digraphId: "th-unvoiced",
    digraphPosition: "initial",
    syllables: ["three"],
    phonemes: ["th", "r", "ee"],
    difficulty: 2,
    imageKeyword: "three 3",
  },
  {
    id: "th-bath",
    word: "bath",
    digraphId: "th-unvoiced",
    digraphPosition: "final",
    syllables: ["bath"],
    phonemes: ["b", "a", "th"],
    difficulty: 1,
    imageKeyword: "bath tub",
  },
  {
    id: "th-path",
    word: "path",
    digraphId: "th-unvoiced",
    digraphPosition: "final",
    syllables: ["path"],
    phonemes: ["p", "a", "th"],
    difficulty: 1,
    imageKeyword: "path trail",
  },
  {
    id: "th-math",
    word: "math",
    digraphId: "th-unvoiced",
    digraphPosition: "final",
    syllables: ["math"],
    phonemes: ["m", "a", "th"],
    difficulty: 1,
    imageKeyword: "math numbers",
  },
  {
    id: "th-teeth",
    word: "teeth",
    digraphId: "th-unvoiced",
    digraphPosition: "final",
    syllables: ["teeth"],
    phonemes: ["t", "ee", "th"],
    difficulty: 2,
    imageKeyword: "teeth smile",
  },
  {
    id: "th-mouth",
    word: "mouth",
    digraphId: "th-unvoiced",
    digraphPosition: "final",
    syllables: ["mouth"],
    phonemes: ["m", "ou", "th"],
    difficulty: 2,
    imageKeyword: "mouth",
  },

  // WH words (12 words)
  {
    id: "wh-when",
    word: "when",
    digraphId: "wh",
    digraphPosition: "initial",
    syllables: ["when"],
    phonemes: ["wh", "e", "n"],
    difficulty: 1,
    imageKeyword: "clock when",
  },
  {
    id: "wh-what",
    word: "what",
    digraphId: "wh",
    digraphPosition: "initial",
    syllables: ["what"],
    phonemes: ["wh", "a", "t"],
    difficulty: 1,
    imageKeyword: "question mark",
  },
  {
    id: "wh-why",
    word: "why",
    digraphId: "wh",
    digraphPosition: "initial",
    syllables: ["why"],
    phonemes: ["wh", "y"],
    difficulty: 1,
    imageKeyword: "question why",
  },
  {
    id: "wh-which",
    word: "which",
    digraphId: "wh",
    digraphPosition: "initial",
    syllables: ["which"],
    phonemes: ["wh", "i", "ch"],
    difficulty: 2,
    imageKeyword: "choice which",
  },
  {
    id: "wh-where",
    word: "where",
    digraphId: "wh",
    digraphPosition: "initial",
    syllables: ["where"],
    phonemes: ["wh", "air"],
    difficulty: 2,
    imageKeyword: "map where",
  },
  {
    id: "wh-while",
    word: "while",
    digraphId: "wh",
    digraphPosition: "initial",
    syllables: ["while"],
    phonemes: ["wh", "i", "le"],
    difficulty: 2,
    imageKeyword: "time while",
  },
  {
    id: "wh-whale",
    word: "whale",
    digraphId: "wh",
    digraphPosition: "initial",
    syllables: ["whale"],
    phonemes: ["wh", "a", "le"],
    difficulty: 2,
    imageKeyword: "whale ocean",
  },
  {
    id: "wh-wheel",
    word: "wheel",
    digraphId: "wh",
    digraphPosition: "initial",
    syllables: ["wheel"],
    phonemes: ["wh", "ee", "l"],
    difficulty: 2,
    imageKeyword: "wheel",
  },
  {
    id: "wh-white",
    word: "white",
    digraphId: "wh",
    digraphPosition: "initial",
    syllables: ["white"],
    phonemes: ["wh", "i", "te"],
    difficulty: 2,
    imageKeyword: "white color",
  },
  {
    id: "wh-whisper",
    word: "whisper",
    digraphId: "wh",
    digraphPosition: "initial",
    syllables: ["whis", "per"],
    phonemes: ["wh", "i", "s", "p", "er"],
    difficulty: 3,
    imageKeyword: "whisper quiet",
  },
  {
    id: "wh-whistle",
    word: "whistle",
    digraphId: "wh",
    digraphPosition: "initial",
    syllables: ["whis", "tle"],
    phonemes: ["wh", "i", "s", "le"],
    difficulty: 3,
    imageKeyword: "whistle",
  },
  {
    id: "wh-wheat",
    word: "wheat",
    digraphId: "wh",
    digraphPosition: "initial",
    syllables: ["wheat"],
    phonemes: ["wh", "ea", "t"],
    difficulty: 2,
    imageKeyword: "wheat grain",
  },

  // PH words (10 words)
  {
    id: "ph-phone",
    word: "phone",
    digraphId: "ph",
    digraphPosition: "initial",
    syllables: ["phone"],
    phonemes: ["ph", "o", "ne"],
    difficulty: 2,
    imageKeyword: "phone telephone",
  },
  {
    id: "ph-photo",
    word: "photo",
    digraphId: "ph",
    digraphPosition: "initial",
    syllables: ["pho", "to"],
    phonemes: ["ph", "o", "t", "o"],
    difficulty: 3,
    imageKeyword: "photo picture",
  },
  {
    id: "ph-graph",
    word: "graph",
    digraphId: "ph",
    digraphPosition: "final",
    syllables: ["graph"],
    phonemes: ["g", "r", "a", "ph"],
    difficulty: 2,
    imageKeyword: "graph chart",
  },
  {
    id: "ph-dolphin",
    word: "dolphin",
    digraphId: "ph",
    digraphPosition: "medial",
    syllables: ["dol", "phin"],
    phonemes: ["d", "o", "l", "ph", "i", "n"],
    difficulty: 3,
    imageKeyword: "dolphin",
  },
  {
    id: "ph-elephant",
    word: "elephant",
    digraphId: "ph",
    digraphPosition: "medial",
    syllables: ["el", "e", "phant"],
    phonemes: ["e", "l", "e", "ph", "a", "n", "t"],
    difficulty: 3,
    imageKeyword: "elephant",
  },
  {
    id: "ph-alphabet",
    word: "alphabet",
    digraphId: "ph",
    digraphPosition: "medial",
    syllables: ["al", "pha", "bet"],
    phonemes: ["a", "l", "ph", "a", "b", "e", "t"],
    difficulty: 3,
    imageKeyword: "alphabet letters",
  },
  {
    id: "ph-phonics",
    word: "phonics",
    digraphId: "ph",
    digraphPosition: "initial",
    syllables: ["pho", "nics"],
    phonemes: ["ph", "o", "n", "i", "cs"],
    difficulty: 3,
    imageKeyword: "phonics reading",
  },
  {
    id: "ph-trophy",
    word: "trophy",
    digraphId: "ph",
    digraphPosition: "medial",
    syllables: ["tro", "phy"],
    phonemes: ["t", "r", "o", "ph", "y"],
    difficulty: 3,
    imageKeyword: "trophy award",
  },
  {
    id: "ph-phrase",
    word: "phrase",
    digraphId: "ph",
    digraphPosition: "initial",
    syllables: ["phrase"],
    phonemes: ["ph", "r", "a", "se"],
    difficulty: 3,
    imageKeyword: "phrase words",
  },
  {
    id: "ph-nephew",
    word: "nephew",
    digraphId: "ph",
    digraphPosition: "medial",
    syllables: ["neph", "ew"],
    phonemes: ["n", "e", "ph", "ew"],
    difficulty: 3,
    imageKeyword: "nephew boy",
  },

  // CK words (13 words)
  {
    id: "ck-duck",
    word: "duck",
    digraphId: "ck",
    digraphPosition: "final",
    syllables: ["duck"],
    phonemes: ["d", "u", "ck"],
    difficulty: 1,
    imageKeyword: "duck bird",
  },
  {
    id: "ck-sock",
    word: "sock",
    digraphId: "ck",
    digraphPosition: "final",
    syllables: ["sock"],
    phonemes: ["s", "o", "ck"],
    difficulty: 1,
    imageKeyword: "sock",
  },
  {
    id: "ck-rock",
    word: "rock",
    digraphId: "ck",
    digraphPosition: "final",
    syllables: ["rock"],
    phonemes: ["r", "o", "ck"],
    difficulty: 1,
    imageKeyword: "rock stone",
  },
  {
    id: "ck-kick",
    word: "kick",
    digraphId: "ck",
    digraphPosition: "final",
    syllables: ["kick"],
    phonemes: ["k", "i", "ck"],
    difficulty: 1,
    imageKeyword: "kick ball",
  },
  {
    id: "ck-pick",
    word: "pick",
    digraphId: "ck",
    digraphPosition: "final",
    syllables: ["pick"],
    phonemes: ["p", "i", "ck"],
    difficulty: 1,
    imageKeyword: "pick choose",
  },
  {
    id: "ck-sick",
    word: "sick",
    digraphId: "ck",
    digraphPosition: "final",
    syllables: ["sick"],
    phonemes: ["s", "i", "ck"],
    difficulty: 1,
    imageKeyword: "sick ill",
  },
  {
    id: "ck-luck",
    word: "luck",
    digraphId: "ck",
    digraphPosition: "final",
    syllables: ["luck"],
    phonemes: ["l", "u", "ck"],
    difficulty: 1,
    imageKeyword: "luck clover",
  },
  {
    id: "ck-truck",
    word: "truck",
    digraphId: "ck",
    digraphPosition: "final",
    syllables: ["truck"],
    phonemes: ["t", "r", "u", "ck"],
    difficulty: 2,
    imageKeyword: "truck",
  },
  {
    id: "ck-clock",
    word: "clock",
    digraphId: "ck",
    digraphPosition: "final",
    syllables: ["clock"],
    phonemes: ["c", "l", "o", "ck"],
    difficulty: 2,
    imageKeyword: "clock time",
  },
  {
    id: "ck-block",
    word: "block",
    digraphId: "ck",
    digraphPosition: "final",
    syllables: ["block"],
    phonemes: ["b", "l", "o", "ck"],
    difficulty: 2,
    imageKeyword: "block toy",
  },
  {
    id: "ck-brick",
    word: "brick",
    digraphId: "ck",
    digraphPosition: "final",
    syllables: ["brick"],
    phonemes: ["b", "r", "i", "ck"],
    difficulty: 2,
    imageKeyword: "brick",
  },
  {
    id: "ck-chick",
    word: "chick",
    digraphId: "ck",
    digraphPosition: "final",
    syllables: ["chick"],
    phonemes: ["ch", "i", "ck"],
    difficulty: 2,
    imageKeyword: "chick baby chicken",
  },
  {
    id: "ck-pocket",
    word: "pocket",
    digraphId: "ck",
    digraphPosition: "medial",
    syllables: ["pock", "et"],
    phonemes: ["p", "o", "ck", "e", "t"],
    difficulty: 3,
    imageKeyword: "pocket",
  },

  // NG words (13 words)
  {
    id: "ng-ring",
    word: "ring",
    digraphId: "ng",
    digraphPosition: "final",
    syllables: ["ring"],
    phonemes: ["r", "i", "ng"],
    difficulty: 1,
    imageKeyword: "ring jewelry",
  },
  {
    id: "ng-sing",
    word: "sing",
    digraphId: "ng",
    digraphPosition: "final",
    syllables: ["sing"],
    phonemes: ["s", "i", "ng"],
    difficulty: 1,
    imageKeyword: "sing music",
  },
  {
    id: "ng-king",
    word: "king",
    digraphId: "ng",
    digraphPosition: "final",
    syllables: ["king"],
    phonemes: ["k", "i", "ng"],
    difficulty: 1,
    imageKeyword: "king crown",
  },
  {
    id: "ng-wing",
    word: "wing",
    digraphId: "ng",
    digraphPosition: "final",
    syllables: ["wing"],
    phonemes: ["w", "i", "ng"],
    difficulty: 1,
    imageKeyword: "wing bird",
  },
  {
    id: "ng-song",
    word: "song",
    digraphId: "ng",
    digraphPosition: "final",
    syllables: ["song"],
    phonemes: ["s", "o", "ng"],
    difficulty: 1,
    imageKeyword: "song music",
  },
  {
    id: "ng-long",
    word: "long",
    digraphId: "ng",
    digraphPosition: "final",
    syllables: ["long"],
    phonemes: ["l", "o", "ng"],
    difficulty: 1,
    imageKeyword: "long",
  },
  {
    id: "ng-thing",
    word: "thing",
    digraphId: "ng",
    digraphPosition: "final",
    syllables: ["thing"],
    phonemes: ["th", "i", "ng"],
    difficulty: 2,
    imageKeyword: "thing object",
  },
  {
    id: "ng-bring",
    word: "bring",
    digraphId: "ng",
    digraphPosition: "final",
    syllables: ["bring"],
    phonemes: ["b", "r", "i", "ng"],
    difficulty: 2,
    imageKeyword: "bring carry",
  },
  {
    id: "ng-spring",
    word: "spring",
    digraphId: "ng",
    digraphPosition: "final",
    syllables: ["spring"],
    phonemes: ["s", "p", "r", "i", "ng"],
    difficulty: 2,
    imageKeyword: "spring season",
  },
  {
    id: "ng-string",
    word: "string",
    digraphId: "ng",
    digraphPosition: "final",
    syllables: ["string"],
    phonemes: ["s", "t", "r", "i", "ng"],
    difficulty: 2,
    imageKeyword: "string",
  },
  {
    id: "ng-swing",
    word: "swing",
    digraphId: "ng",
    digraphPosition: "final",
    syllables: ["swing"],
    phonemes: ["s", "w", "i", "ng"],
    difficulty: 2,
    imageKeyword: "swing playground",
  },
  {
    id: "ng-young",
    word: "young",
    digraphId: "ng",
    digraphPosition: "final",
    syllables: ["young"],
    phonemes: ["y", "ou", "ng"],
    difficulty: 2,
    imageKeyword: "young child",
  },
  {
    id: "ng-along",
    word: "along",
    digraphId: "ng",
    digraphPosition: "final",
    syllables: ["a", "long"],
    phonemes: ["a", "l", "o", "ng"],
    difficulty: 3,
    imageKeyword: "along path",
  },
];

// Helper functions
export function getDigraphById(id: string): DigraphItem | undefined {
  return DIGRAPHS.find((d) => d.id === id);
}

export function getWordsByDigraph(digraphId: string): DigraphWord[] {
  return DIGRAPH_WORDS.filter((w) => w.digraphId === digraphId);
}

export function getWordsByDifficulty(difficulty: 1 | 2 | 3): DigraphWord[] {
  return DIGRAPH_WORDS.filter((w) => w.difficulty === difficulty);
}

export function getRandomDigraphWords(count: number, digraphId?: string): DigraphWord[] {
  let words = digraphId ? getWordsByDigraph(digraphId) : [...DIGRAPH_WORDS];
  const shuffled = words.sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

export function getDigraphForWord(word: string): DigraphItem | undefined {
  const wordData = DIGRAPH_WORDS.find((w) => w.word === word);
  if (!wordData) return undefined;
  return getDigraphById(wordData.digraphId);
}
